#%%
# AUTO-GENERATED by generate_dynamical_system.py
# Source: /Users/tiago/Desktop/AM-TUM/Code/MORFE_jl/examples/07_parametric_arch/results/data/arch_h0.005/R_coefficients.csv
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[4] / "pyhbm" / "pyhbm" / "src"))

import numpy as np
from numpy import array, concatenate
from pyhbm.dynamical_system import FirstOrderODE

# zdot = f(z, zconj)
# Input x, y 
# z = x + i y, zconj = x - i y
# xdot = Re(f(z, zconj))
# ydot = Im(f(z, zconj))

class ParametricArchBackbone(FirstOrderODE):
    """
    Conservative autonomous ROM for the parametric arch backbone (pyhbm HBM).

    State (x0, x1) = (Re(z1), Im(z1)) where z1 = x0 + i*x1.
    Realification convention: z1 = x0 + i*x1, z2 = x0 - i*x1.

    Dynamics from R1 component of the MORFE ROM:
        z      = x0 + 1j*x1
        z_conj = x0 - 1j*x1
        y      = R1(z, z_conj, theta)
        x0dot  = y.real
        x1dot  = y.imag

    theta  : arch-height parameter, frozen at construction.
             theta = 0  -> base arch (h0_L_ratio from main.jl)
             theta = -1 -> straight beam
             theta = +1 -> doubled arch height

    z_truncation_order    : include nonlinear z-degree up to this order (default 7)
    theta_truncation_order: include theta powers up to this order (default 7);
                            self.theta_p entries beyond this stay 0.0.
    """

    is_real_valued = True

    def __init__(self, theta: float = 0.0,
                 z_truncation_order: int = 7,
                 theta_truncation_order: int = 7):
        self.theta = theta
        theta = float(theta)
        self.z_truncation_order = z_truncation_order
        theta_truncation_order = min(theta_truncation_order, 7)
        
        self.theta_p = [0.0] * 8
        self.theta_p[0] = 1.0
        for i in range(1, theta_truncation_order + 1):
            self.theta_p[i] = self.theta_p[i - 1] * theta
            
        self.omega0 = \
            6.187053874170462e-01 + \
            1.316408701948978e-01*self.theta_p[1] + \
            5.169975264656677e-02*self.theta_p[2] + \
            -1.111674081989460e-02*self.theta_p[3] + \
            1.750458302663907e-04*self.theta_p[4] + \
            8.911023547465547e-04*self.theta_p[5] + \
            -3.042121619692297e-04*self.theta_p[6] + \
            -6.596390278217023e-06*self.theta_p[7]
            
        self.linear_coefficient = array([
            [0.0, -self.omega0],
            [self.omega0,  0.0],
        ])
        
        self.dimension = 2
        self.polynomial_degree = 7

    def external_term(self, adimensional_time: np.ndarray) -> np.ndarray:
        zeros = np.zeros_like(adimensional_time)
        return array([[zeros, zeros]]).transpose()

    def linear_term(self, state: np.ndarray) -> np.ndarray:
        return self.linear_coefficient @ state

    def _pack_real_imag(self, y: np.ndarray) -> np.ndarray:
        return concatenate((y.real, y.imag), axis=-2)

    def _wirtinger_to_jacobian(self, dy_dz: np.ndarray, dy_dz_conj: np.ndarray) -> np.ndarray:
        dy_dx0 = dy_dz + dy_dz_conj
        dy_dx1 = 1j * (dy_dz - dy_dz_conj)
        jacobian0 = concatenate((dy_dx0.real, dy_dx1.real), axis=-1)
        jacobian1 = concatenate((dy_dx0.imag, dy_dx1.imag), axis=-1)
        return concatenate((jacobian0, jacobian1), axis=-2)

    def nonlinear_term(self, state: np.ndarray, adimensional_time: np.ndarray) -> np.ndarray:
        x0 = state[..., 0:1, :]
        x1 = state[..., 1:2, :]
        z = x0 + 1j*x1
        z_conj = x0 - 1j*x1
        y = np.zeros_like(z)

        if self.z_truncation_order < 3:
            return self._pack_real_imag(y)
        
        y += (\
        -1.957691324885887e-06*1j+\
        -3.972120797349967e-05*1j*self.theta_p[1]+\
        +1.360162017556548e-05*1j*self.theta_p[2]+\
        +1.256514179581998e-05*1j*self.theta_p[3]+\
        -1.143288994346553e-05*1j*self.theta_p[4]+\
        +1.443168602740337e-06*1j*self.theta_p[5]+\
        +2.736533594091751e-06*1j*self.theta_p[6]+\
        -1.691569134614786e-06*1j*self.theta_p[7] ) * z**2*z_conj

        if self.z_truncation_order < 5:
            return self._pack_real_imag(y)

        y += (\
        +3.725110917834218e-09*1j+\
        -1.298354210188597e-10*1j*self.theta_p[1]+\
        -9.667634152057669e-09*1j*self.theta_p[2]+\
        +6.522514192702954e-09*1j*self.theta_p[3]+\
        +4.543368967786132e-09*1j*self.theta_p[4]+\
        -7.579920022827899e-09*1j*self.theta_p[5]+\
        +2.049137228934692e-09*1j*self.theta_p[6] ) * z**3*z_conj**2

        if self.z_truncation_order < 7:
            return self._pack_real_imag(y)

        y += (\
        -2.210622716618603e-13*1j+\
        +1.686103924288444e-12*1j*self.theta_p[1]+\
        -4.172435626847252e-13*1j*self.theta_p[2]+\
        -3.967760042070108e-12*1j*self.theta_p[3]+\
        +3.960092362136116e-12*1j*self.theta_p[4] ) * z**4*z_conj**3

        return self._pack_real_imag(y)

    def jacobian_nonlinear_term(self, state: np.ndarray, adimensional_time: np.ndarray) -> np.ndarray:
        x0 = state[..., 0:1, :]
        x1 = state[..., 1:2, :]
        z = x0 + 1j*x1
        z_conj = x0 - 1j*x1
        dy_dz = np.zeros_like(z)
        dy_dz_conj = np.zeros_like(z)

        if self.z_truncation_order < 3:
            return self._wirtinger_to_jacobian(dy_dz, dy_dz_conj)

        dy_dz += \
        -3.915382649771775e-06*1j*z*z_conj+\
        -7.944241594699934e-05*1j*z*z_conj*self.theta_p[1]+\
        +2.720324035113096e-05*1j*z*z_conj*self.theta_p[2]+\
        +2.513028359163996e-05*1j*z*z_conj*self.theta_p[3]+\
        -2.286577988693105e-05*1j*z*z_conj*self.theta_p[4]+\
        +2.886337205480674e-06*1j*z*z_conj*self.theta_p[5]+\
        +5.473067188183501e-06*1j*z*z_conj*self.theta_p[6]+\
        -3.383138269229572e-06*1j*z*z_conj*self.theta_p[7]
        dy_dz_conj += \
        -1.957691324885887e-06*1j*z**2+\
        -3.972120797349967e-05*1j*z**2*self.theta_p[1]+\
        +1.360162017556548e-05*1j*z**2*self.theta_p[2]+\
        +1.256514179581998e-05*1j*z**2*self.theta_p[3]+\
        -1.143288994346553e-05*1j*z**2*self.theta_p[4]+\
        +1.443168602740337e-06*1j*z**2*self.theta_p[5]+\
        +2.736533594091751e-06*1j*z**2*self.theta_p[6]+\
        -1.691569134614786e-06*1j*z**2*self.theta_p[7]

        if self.z_truncation_order < 5:
            return self._wirtinger_to_jacobian(dy_dz, dy_dz_conj)

        dy_dz += \
        +1.117533275350265e-08*1j**2+\
        -3.895062630565790e-10*1j**2*self.theta_p[1]+\
        -2.900290245617301e-08*1j**2*self.theta_p[2]+\
        +1.956754257810886e-08*1j**2*self.theta_p[3]+\
        +1.363010690335840e-08*1j**2*self.theta_p[4]+\
        -2.273976006848370e-08*1j**2*self.theta_p[5]+\
        +6.147411686804075e-09*1j**2*self.theta_p[6]
        dy_dz_conj += \
        +7.450221835668436e-09*1j*z**3*z_conj+\
        -2.596708420377193e-10*1j*z**3*z_conj*self.theta_p[1]+\
        -1.933526830411534e-08*1j*z**3*z_conj*self.theta_p[2]+\
        +1.304502838540591e-08*1j*z**3*z_conj*self.theta_p[3]+\
        +9.086737935572263e-09*1j*z**3*z_conj*self.theta_p[4]+\
        -1.515984004565580e-08*1j*z**3*z_conj*self.theta_p[5]+\
        +4.098274457869383e-09*1j*z**3*z_conj*self.theta_p[6]

        if self.z_truncation_order < 7:
            return self._wirtinger_to_jacobian(dy_dz, dy_dz_conj)

        dy_dz += \
        -8.842490866474410e-13*1j*z**3*z_conj**3+\
        +6.744415697153775e-12*1j*z**3*z_conj**3*self.theta_p[1]+\
        -1.668974250738901e-12*1j*z**3*z_conj**3*self.theta_p[2]+\
        -1.587104016828043e-11*1j*z**3*z_conj**3*self.theta_p[3]+\
        +1.584036944854446e-11*1j*z**3*z_conj**3*self.theta_p[4]
        dy_dz_conj += \
        -6.631868149855807e-13*1j*z**4*z_conj**2+\
        +5.058311772865331e-12*1j*z**4*z_conj**2*self.theta_p[1]+\
        -1.251730688054175e-12*1j*z**4*z_conj**2*self.theta_p[2]+\
        -1.190328012621032e-11*1j*z**4*z_conj**2*self.theta_p[3]+\
        +1.188027708640835e-11*1j*z**4*z_conj**2*self.theta_p[4]

        return self._wirtinger_to_jacobian(dy_dz, dy_dz_conj)

    def all_terms(self, state: np.ndarray, adimensional_time: np.ndarray) -> np.ndarray:
        return self.linear_term(state) + self.nonlinear_term(state, adimensional_time)
    
    
    
"""
exp_1,exp_2,R1_re,R1_im,R2_re,R2_im
1,0,-0.0,0.5489204110069565,0.0,0.0
2,1,0.0,2.6578561528211636e-5,0.0,0.0
3,2,0.0,-2.00197820605989e-9,0.0,0.0
4,3,0.0,2.429750289428825e-13,0.0,0.0
"""
class ArchBackbone0mm(FirstOrderODE):

    is_real_valued = True

    def __init__(self):
            
        self.omega0 = 0.5489204110069565
            
        self.linear_coefficient = array([
            [0.0, -self.omega0],
            [self.omega0,  0.0],
        ])
        
        self.dimension = 2
        self.polynomial_degree = 7

    def external_term(self, adimensional_time: np.ndarray) -> np.ndarray:
        zeros = np.zeros_like(adimensional_time)
        return array([[zeros, zeros]]).transpose()

    def linear_term(self, state: np.ndarray) -> np.ndarray:
        return self.linear_coefficient @ state

    def _pack_real_imag(self, y: np.ndarray) -> np.ndarray:
        return concatenate((y.real, y.imag), axis=-2)

    def _wirtinger_to_jacobian(self, dy_dz: np.ndarray, dy_dz_conj: np.ndarray) -> np.ndarray:
        dy_dx0 = dy_dz + dy_dz_conj
        dy_dx1 = 1j * (dy_dz - dy_dz_conj)
        jacobian0 = concatenate((dy_dx0.real, dy_dx1.real), axis=-1)
        jacobian1 = concatenate((dy_dx0.imag, dy_dx1.imag), axis=-1)
        return concatenate((jacobian0, jacobian1), axis=-2)

    def nonlinear_term(self, state: np.ndarray, adimensional_time: np.ndarray) -> np.ndarray:
        x0 = state[..., 0:1, :]
        x1 = state[..., 1:2, :]
        z = x0 + 1j*x1
        z_conj = x0 - 1j*x1
        y = np.zeros_like(z)
        
        """
        exp_1,exp_2,R1_re,R1_im,R2_re,R2_im
        1,0,-0.0,0.5489204110069565,0.0,0.0
        2,1,0.0,2.6578561528211636e-5,0.0,0.0
        3,2,0.0,-2.00197820605989e-9,0.0,0.0
        4,3,0.0,2.429750289428825e-13,0.0,0.0
        """
        
        y += \
        +2.6578561528211636e-5*1j * z**2*z_conj \
        -2.00197820605989e-9*1j * z**3*z_conj**2 \
        +2.429750289428825e-13*1j * z**4*z_conj**3

        return self._pack_real_imag(y)

    def jacobian_nonlinear_term(self, state: np.ndarray, adimensional_time: np.ndarray) -> np.ndarray:
        x0 = state[..., 0:1, :]
        x1 = state[..., 1:2, :]
        z = x0 + 1j*x1
        z_conj = x0 - 1j*x1
        dy_dz = np.zeros_like(z)
        dy_dz_conj = np.zeros_like(z)
        
        dy_dz += \
        +2.6578561528211636e-5*1j * 2* z*z_conj \
        -2.00197820605989e-9*1j * 3* z**2*z_conj**2 \
        +2.429750289428825e-13*1j * 4* z**3*z_conj**3
        
        dy_dz_conj += \
        +2.6578561528211636e-5*1j * z**2 \
        -2.00197820605989e-9*1j * 2 * z**3*z_conj \
        +2.429750289428825e-13*1j * 3 * z**4*z_conj**2

        return self._wirtinger_to_jacobian(dy_dz, dy_dz_conj)

    def all_terms(self, state: np.ndarray, adimensional_time: np.ndarray) -> np.ndarray:
        return self.linear_term(state) + self.nonlinear_term(state, adimensional_time)


"""
exp_1,exp_2,R1_re,R1_im,R2_re,R2_im
1,0,-0.0,0.6187053874170463,0.0,0.0
2,1,0.0,-1.9576913248652765e-6,0.0,0.0
3,2,0.0,3.725085861231001e-9,0.0,0.0
4,3,0.0,-2.210450822951099e-13,0.0,0.0
"""
class ArchBackbone5mm(FirstOrderODE):

    is_real_valued = True

    def __init__(self):
            
        self.omega0 = 0.6187053874170463
            
        self.linear_coefficient = array([
            [0.0, -self.omega0],
            [self.omega0,  0.0],
        ])
        
        self.dimension = 2
        self.polynomial_degree = 7

    def external_term(self, adimensional_time: np.ndarray) -> np.ndarray:
        zeros = np.zeros_like(adimensional_time)
        return array([[zeros, zeros]]).transpose()

    def linear_term(self, state: np.ndarray) -> np.ndarray:
        return self.linear_coefficient @ state

    def _pack_real_imag(self, y: np.ndarray) -> np.ndarray:
        return concatenate((y.real, y.imag), axis=-2)

    def _wirtinger_to_jacobian(self, dy_dz: np.ndarray, dy_dz_conj: np.ndarray) -> np.ndarray:
        dy_dx0 = dy_dz + dy_dz_conj
        dy_dx1 = 1j * (dy_dz - dy_dz_conj)
        jacobian0 = concatenate((dy_dx0.real, dy_dx1.real), axis=-1)
        jacobian1 = concatenate((dy_dx0.imag, dy_dx1.imag), axis=-1)
        return concatenate((jacobian0, jacobian1), axis=-2)

    def nonlinear_term(self, state: np.ndarray, adimensional_time: np.ndarray) -> np.ndarray:
        x0 = state[..., 0:1, :]
        x1 = state[..., 1:2, :]
        z = x0 + 1j*x1
        z_conj = x0 - 1j*x1
        y = np.zeros_like(z)
        
        """
        exp_1,exp_2,R1_re,R1_im,R2_re,R2_im
        1,0,-0.0,0.6187053874170463,0.0,0.0
        2,1,0.0,-1.9576913248652765e-6,0.0,0.0
        3,2,0.0,3.725085861231001e-9,0.0,0.0
        4,3,0.0,-2.210450822951099e-13,0.0,0.0
        """
        
        y += \
        -1.9576913248652765e-6 *1j * z**2*z_conj \
        +3.725085861231001e-9 *1j * z**3*z_conj**2 \
        -2.210450822951099e-13 *1j * z**4*z_conj**3

        return self._pack_real_imag(y)

    def jacobian_nonlinear_term(self, state: np.ndarray, adimensional_time: np.ndarray) -> np.ndarray:
        x0 = state[..., 0:1, :]
        x1 = state[..., 1:2, :]
        z = x0 + 1j*x1
        z_conj = x0 - 1j*x1
        dy_dz = np.zeros_like(z)
        dy_dz_conj = np.zeros_like(z)
        
        dy_dz += \
        -1.9576913248652765e-6 *1j * 2* z*z_conj \
        +3.725085861231001e-9 *1j * 3* z**2*z_conj**2 \
        -2.210450822951099e-13 *1j * 4* z**3*z_conj**3
        
        dy_dz_conj += \
        -1.9576913248652765e-6 *1j * z**2 \
        +3.725085861231001e-9 *1j * 2 * z**3*z_conj \
        -2.210450822951099e-13 *1j * 3 * z**4*z_conj**2

        return self._wirtinger_to_jacobian(dy_dz, dy_dz_conj)

    def all_terms(self, state: np.ndarray, adimensional_time: np.ndarray) -> np.ndarray:
        return self.linear_term(state) + self.nonlinear_term(state, adimensional_time)


"""
exp_1,exp_2,R1_re,R1_im,R2_re,R2_im
1,0,-0.0,0.7917136033608646,0.0,0.0
2,1,-0.0,-3.140205904986185e-5,0.0,0.0
3,2,-0.0,6.402979237671709e-10,0.0,0.0
4,3,-0.0,3.365053378606641e-13,0.0,0.0
"""
class ArchBackbone10mm(FirstOrderODE):

    is_real_valued = True

    def __init__(self):
            
        self.omega0 = 0.7917136033608646
            
        self.linear_coefficient = array([
            [0.0, -self.omega0],
            [self.omega0,  0.0],
        ])
        
        self.dimension = 2
        self.polynomial_degree = 7

    def external_term(self, adimensional_time: np.ndarray) -> np.ndarray:
        zeros = np.zeros_like(adimensional_time)
        return array([[zeros, zeros]]).transpose()

    def linear_term(self, state: np.ndarray) -> np.ndarray:
        return self.linear_coefficient @ state

    def _pack_real_imag(self, y: np.ndarray) -> np.ndarray:
        return concatenate((y.real, y.imag), axis=-2)

    def _wirtinger_to_jacobian(self, dy_dz: np.ndarray, dy_dz_conj: np.ndarray) -> np.ndarray:
        dy_dx0 = dy_dz + dy_dz_conj
        dy_dx1 = 1j * (dy_dz - dy_dz_conj)
        jacobian0 = concatenate((dy_dx0.real, dy_dx1.real), axis=-1)
        jacobian1 = concatenate((dy_dx0.imag, dy_dx1.imag), axis=-1)
        return concatenate((jacobian0, jacobian1), axis=-2)

    def nonlinear_term(self, state: np.ndarray, adimensional_time: np.ndarray) -> np.ndarray:
        x0 = state[..., 0:1, :]
        x1 = state[..., 1:2, :]
        z = x0 + 1j*x1
        z_conj = x0 - 1j*x1
        y = np.zeros_like(z)
        
        """
        exp_1,exp_2,R1_re,R1_im,R2_re,R2_im
        1,0,-0.0,0.7917136033608646,0.0,0.0
        2,1,-0.0,-3.140205904986185e-5,0.0,0.0
        3,2,-0.0,6.402979237671709e-10,0.0,0.0
        4,3,-0.0,3.365053378606641e-13,0.0,0.0
        """
        
        y += \
        -3.140205904986185e-5 *1j * z**2*z_conj \
        +6.402979237671709e-10 *1j * z**3*z_conj**2 \
        +3.365053378606641e-13 *1j * z**4*z_conj**3
            

        return self._pack_real_imag(y)

    def jacobian_nonlinear_term(self, state: np.ndarray, adimensional_time: np.ndarray) -> np.ndarray:
        x0 = state[..., 0:1, :]
        x1 = state[..., 1:2, :]
        z = x0 + 1j*x1
        z_conj = x0 - 1j*x1
        dy_dz = np.zeros_like(z)
        dy_dz_conj = np.zeros_like(z)
        
        dy_dz += \
        -3.140205904986185e-5 *1j * 2 * z*z_conj \
        +6.402979237671709e-10 *1j * 3 * z**2*z_conj**2 \
        +3.365053378606641e-13 *1j * 4 * z**3*z_conj**3
        
        dy_dz_conj += \
        -3.140205904986185e-5 *1j * z**2 \
        +6.402979237671709e-10 *1j * 2 * z**3*z_conj \
        +3.365053378606641e-13 *1j * 3 * z**4*z_conj**2

        return self._wirtinger_to_jacobian(dy_dz, dy_dz_conj)

    def all_terms(self, state: np.ndarray, adimensional_time: np.ndarray) -> np.ndarray:
        return self.linear_term(state) + self.nonlinear_term(state, adimensional_time)

# %%
